// PRODUCTS data shared between index.html and product.html
window.PRODUCTS = [
  {
    id: 1,
    name: "NETFLIX PREMIUM",
    category: "Streaming",
    tagline: "Khusus TV, pembelian 1 profil (tidak bisa tambahan)",
    desc: "Kualitas Ultra HD 4K, aman dan bergaransi penuh.",
    icon: "fa-solid fa-film",
    color: "from-red-500 to-rose-700",
    variants: [
      { name: "1 Bulan (sharing)", price: 69000 },
      { name: "2 Bulan (1 Profil)", price: 199000 },
      { name: "3 Bulan (1 Profil)", price: 299000 },
      { name: "1 Bulan (Private)", price: 99000 },
    ],
  },
  {
    id: 2,
    name: "CANVA PRO",
    category: "Desain",
    tagline: "Garansi 1 Tahun penuh",
    desc: "Akses ribuan aset desain premium, foto, dan template profesional ( untuk 1 tahun bonus akun Youtube, Viu ,Spotify).",
    icon: "fa-solid fa-palette",
    color: "from-teal-500 to-cyan-600",
    variants: [{ name: "1 Bulan", price: 99000 }],
  },
  {
    id: 3,
    name: "CAPCUT PRO",
    category: "Desain",
    tagline: "Akun Private Full Garansi",
    desc: "Akses transisi premium, efek eksklusif, dan ekspor kualitas tinggi ( untuk 1 tahun bonus akun Youtube, Viu ,Spotif).",
    icon: "fa-solid fa-scissors",
    color: "from-sky-500 to-indigo-600",
    variants: [{ name: "1 Bulan", price: 99000 }],
  },
  {
    id: 4,
    name: "VIU VIP",
    category: "Streaming",
    tagline: "Akses Drama Korea Terbaru & Terbaik",
    desc: "Tanpa iklan, kualitas full HD dengan teks terjemahan bahasa Indonesia.",
    icon: "fa-solid fa-tv",
    color: "from-amber-400 to-orange-600",
    variants: [{ name: "Lifetime", price: 99000 }],
  },
  {
    id: 5,
    name: "YOUTUBE PREMIUM & MUSIC",
    category: "Musik",
    tagline: "Full Garansi Penuh",
    desc: "Bebas iklan, putar di latar belakang, dan unduh lagu sepuasnya.",
    icon: "fa-brands fa-youtube",
    color: "from-red-600 to-pink-700",
    variants: [{ name: "1 Bulan (Full Garansi)", price: 69000 }],
  },
  {
    id: 6,
    name: "SPOTIFY PREMIUM",
    category: "Musik",
    tagline: "Akun 1 User / Private",
    desc: "Bebas dengerin musik tanpa jeda iklan, bisa offline dengan bit rate tertinggi.",
    icon: "fa-brands fa-spotify",
    color: "from-emerald-500 to-green-600",
    variants: [
      { name: "1 Bulan ( Student )", price: 25000 },
      { name: "3 Bulan ( H&M )", price: 49000 },
    ],
  },
  {
    id: 8,
    name: "CHATGPT PLUS",
    category: "Kecerdasan Buatan",
    tagline: "GPT-4 & Fitur Premium Baru",
    desc: "Kecepatan prioritas, analisis data tingkat lanjut, dan gambar berkualitas DALL-E.",
    icon: "fa-solid fa-brain",
    color: "from-fuchsia-500 to-purple-600",
    variants: [
      { name: "3 Bulan (100 Voucher)", price: 199000 },
      { name: "3 Bulan (1000 Voucher)", price: 499000 },
    ],
  },
  {
    id: 9,
    name: "GEMINI AI",
    category: "Kecerdasan Buatan",
    tagline: "Google Advanced Private Akun",
    desc: "Integrasi mendalam ekosistem Google untuk hasil analisis luar biasa.",
    icon: "fa-solid fa-wand-magic-sparkles",
    color: "from-blue-500 to-sky-600",
    variants: [{ name: "3 Bulan (Private)", price: 129000 }],
  },
  {
    id: 13,
    name: "PRIME VIDEO",
    category: "Streaming",
    tagline: "Amazon Originals Premium",
    desc: "Bebas nikmati serial kelas dunia dengan kualitas tontonan HDR ultra-tajam.",
    icon: "fa-solid fa-play",
    color: "from-cyan-500 to-blue-500",
    variants: [
      { name: "1 Bulan (1 Profil)", price: 20000 },
      { name: "1 Bulan (Private)", price: 50000 },
    ],
  },
  {
    id: 21,
    name: "VIDIO PLATINUM",
    category: "Streaming",
    tagline: "Akun premium video dengan konten eksklusif",
    desc: "Akses tayangan VIP dengan kualitas HD, garansi aman, dan dukungan prioritas.",
    icon: "fa-solid fa-crown",
    image: "video-platinum.svg",
    color: "from-yellow-500 to-orange-500",
    variants: [{ name: "1 Bulan Platinum", price: 89000 }],
  },
  {
    id: 16,
    name: "HBO MAX",
    category: "Streaming",
    tagline: "Nonton Blockbuster Internasional",
    desc: "Rumah bagi film-film Hollywood legendaris produksi Warner Bros dan DC.",
    icon: "fa-solid fa-compact-disc",
    color: "from-violet-600 to-indigo-800",
    variants: [{ name: "1 Bulan (Max)", price: 69000 }],
  },
  {
    id: 18,
    name: "ZOOM PRO",
    category: "Gaya Hidup",
    tagline: "Full Garansi 1 Bulan",
    desc: "Gelar rapat virtual atau seminar tanpa batas durasi menit dengan lancar.",
    icon: "fa-solid fa-video",
    color: "from-blue-600 to-sky-500",
    variants: [
      { name: "14 Hari", price: 15000 },
      { name: "25 Hari ( Garansi Penuh )", price: 49000 },
    ],
  },
  {
    id: 19,
    name: "SCRIBD PREMIUM",
    category: "Gaya Hidup",
    tagline: "Private Akun Buku & Dokumen Terbesar",
    desc: "Akses tanpa batas ke jutaan buku digital, audiobook, dokumen, dan podcast.",
    icon: "fa-solid fa-book",
    color: "from-teal-600 to-emerald-700",
    variants: [{ name: "1 Bulan (Private)", price: 25000 }],
  },
  {
    id: 20,
    name: "EXPRESS VPN",
    category: "Gaya Hidup",
    tagline: "Private Akun Keamanan Terbaik",
    desc: "Buka segala situs terblokir dengan server berkecepatan super tinggi dan aman.",
    icon: "fa-solid fa-shield",
    color: "from-red-500 to-rose-600",
    variants: [{ name: "1 Bulan (Private)", price: 25000 }],
  },
];
